version: '3.1'

services:
  fiap_restautante:
    image: jessicasalmeida/restaurante:2.0.0
    restart: always
    ports:
      - "8000:8000"
    links:
      - mongo
    networks:
      - mongo-compose-network
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network


  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jessica
      ME_CONFIG_BASICAUTH_PASSWORD: MongoDB2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
      ME_CONFIG_MONGODB_URL: mongodb://root:MongoDB2019!@mongo:27017/
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

networks:
  mongo-compose-network:
    driver: bridge