
apiVersion: v1
kind: Pod
metadata:
  name: fiap_restaurante-bd
  labels:
    app: fiap_restaurante-bd

spec:
  containers:
    - name: banco_dados
      image: mongo
      ports:
        - containerPort: 27017