
apiVersion: v1
kind: Pod
metadata:
  name: fiap-restaurante-bd-pod
  labels:
    app: fiap-restaurante-bd-pod

spec:
  containers:
    - name: mongodb
      image: mongo:4.2.8
      ports:
        - containerPort: 27017