apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-readness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-readness
  template:
    metadata:
      labels:
        app: http-readness
    spec:
      containers:
      - name: restaurante
        image: jessicasalmeida/restaurante:1.0.0 
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          failureThreshold: 3
          periodSeconds: 20

