apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
        - name: restaurante
          image: jessicasalmeida/restaurante:1.0.0
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 60
            periodSeconds: 10
