apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopode-pvc
  labels:
    name: mongopode-pvc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\Users\gjess\Documents\Restaurante\fiap_restaurante\data
