apiVersion: v1
kind: Service
metadata:
  name: svc-fiap-restaurante-bd
  labels:
    app: mongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: fiap-restaurante-bd-pod
    
