apiVersion: v1
kind: Service
metadata:
  name: svc-restaurante-api
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - port: 5000 
      targetPort: 5000
      nodePort: 30001
      protocol: TCP
  selector:
    app: restaurante-api
