apiVersion: v1
kind: Service
metadata:
  name: svc-restaurante-db
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 30000
  selector:
    app: restaurante-db
    
