apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  DB_CONN_STRING: mongodb+srv://admin:fiap_fase3@restaurante-prod-cluste.tcrs6sj.mongodb.net/?retryWrites=true&w=majority&appName=restaurante-prod-cluster
  DB_NAME: restaurante_db
  CART_COLLECTION_NAME: cart
  ORDER_COLLECTION_NAME: order
  PRODUCT_COLLECTION_NAME: produtos
  USER_COLLECTION_NAME: user
  URL: urlteste
