# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-api
  labels:
    app: restaurante-api
spec:
  selector:
    matchLabels:
      app: restaurante-api
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: restaurante-api
    
    spec:
      containers:
        - name: restaurante-api
          image: DOCKER_IMAGE
          imagePullPolicy: Always

          ports: 
            - containerPort: 8000
          env:
            - name: CART_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: CART_COLLECTION_NAME

            - name: ORDER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ORDER_COLLECTION_NAME

            - name: PRODUCT_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PRODUCT_COLLECTION_NAME

            - name: USER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: USER_COLLECTION_NAME

            - name: DB_CONN_STRING
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_CONN_STRING

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: URL


---

apiVersion: v1
kind: Service
metadata:
  name: restaurante-api
spec:
  selector:
    app: restaurante-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000      # tem
      targetPort: 8000
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: restaurante-tgb
spec:
  serviceRef:
    name: restaurante-api
    port: 8000
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:094091489187:loadbalancer/app/restaurante-eks-lb/121841af49feca29