# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: v1
kind: Namespace
metadata:
  name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-api
  namespace: api
  labels:
    app: restaurante-api
spec:
  selector:
    matchLabels:
      app: restaurante-api
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: restaurante-api
    
    spec:
      containers:
        - name: restaurante-api
          image: DOCKER_IMAGE
          ports: 
            - containerPort: 8000
          env:
            - name: CART_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: CART_COLLECTION_NAME

            - name: ORDER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ORDER_COLLECTION_NAME

            - name: PRODUCT_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PRODUCT_COLLECTION_NAME

            - name: USER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: USER_COLLECTION_NAME

            - name: DB_CONN_STRING
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_CONN_STRING

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: URL


---

apiVersion: v1
kind: Service
metadata:
  name: restaurante-api
  namespace: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "restaurante-lb"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
    service.beta.kubernetes.io/aws-load-balancer-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: proxy_protocol_v2.enabled=true
spec:
  selector:
    app: restaurante-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000      # tem
      targetPort: 8000
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: api
  labels:
    app: ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: ingress
    alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
    alb.ingress.kubernetes.io/ssl-redirect: '8000'
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internal
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restaurante-api
                port:
                  number: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-api
  namespace: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000