apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-api
  labels:
    app: restaurante-api
spec:
  selector:
    matchLabels:
      app: restaurante-api
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: restaurante-api
    
    spec:
      containers:
        - name: restaurante-api
          image: DOCKER_IMAGE
          ports: 
            - containerPort: 8000
          env:
            - name: CART_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: CART_COLLECTION_NAME

            - name: ORDER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ORDER_COLLECTION_NAME

            - name: PRODUCT_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PRODUCT_COLLECTION_NAME

            - name: USER_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: USER_COLLECTION_NAME

            - name: DB_CONN_STRING
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_CONN_STRING

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME

            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: URL


---

apiVersion: v1
kind: Service
metadata:
  name: restaurante-api
spec:
  selector:
    app: restaurante-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: ingress
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restaurante-api
                port:
                  number: 8000
.